---
- hosts: all
  become: yes
  gather_facts: no
  vars:
      home: /home/vagrant
      document_root: /vagrant
  pre_tasks:
      - name: 'install python2'
        raw: sudo apt-get -y install python-simplejson
      - name: Update apt cache
        apt:
          update_cache=yes
          cache_valid_time=7200
      - name: Install required packages
        apt: name={{ item }} state=present
        with_items:
         - build-essential
         - git
         - exuberant-ctags
         - tig
         - gdb
         - cgdb
         - make
         - tree
         - htop
         - tmux
         - man-db
  roles:
      - { role: dotfiles, become: no }
      - { role: vim, become: no }
      - { role: cmake, become: no }
      - { role: g++7, become: yes }
      - { role: depend, become: no }
      - { role: youcompleteme, become: no }
