---
- name: Install apt packages for YouCompleteMe vim completion engine
  become: yes
  apt:
    name={{ item }} state=present
  with_items:
    - cmake
    - python3-dev
- name: Check out YouCompleteMe
  git:
    repo=https://github.com/Valloric/YouCompleteMe.git
    dest={{ home }}/src/YouCompleteMe
- name: Download libclang-7.0.0
  get_url:
    url=https://dl.bintray.com/micbou/libclang/libclang-7.0.0-x86_64-unknown-linux-gnu.tar.bz2
    dest={{ home }}/src/YouCompleteMe/third_party/ycmd/cpp/../clang_archives/
- name: Symlink YouCompleteMe to ~/vim/plugged
  file:
    src={{ home }}/src/YouCompleteMe
    dest={{ home }}/.vim/bundle/YouCompleteMe
    state=link
- name: Create clang_archives directory
  file: path={{ home }}/.vim/bundle/YouCompleteMe/third_party/ycmd/clang_archives state=directory
- name: Compile YouCompleteMe binaries
  command: python ./install.py --clang-completer
    chdir={{ home }}/src/YouCompleteMe
    creates={{ home }}/src/YouCompleteMe/third_party/ycmd/ycm_core.so
