---
- name: Add repository
  become: yes
  apt_repository:
    repo=ppa:ubuntu-toolchain-r/test
- name: Update apt cache
  become: yes
  apt:
    update_cache=yes
    cache_valid_time=7200
- name: Install g++-7
  apt: name=g++-7 state=present
- name: Update gcc-7
  become: yes
  command: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
- name: Update g++-7
  become: yes
  command: update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 60
